#!/bin/bash

#after install ubuntu zesty zapus 17.04, we run the following:

################################################################################
#R
################################################################################

grep -q -F 'cran.rstudio.com' /etc/apt/sources.list || sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/" >> /etc/apt/sources.list'
gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
gpg -a --export E084DAB9 | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install r-base texlive libcurl4-openssl-dev
sudo apt-get -y install libcurl4-gnutls-dev libxml2-dev libssl-dev gcc-5-multilib

sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"devtools::install_github('spatstat/spatstat')\""
sudo su - -c "R -e \"install.packages('plotrix', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('Rcpp', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('sets', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('R.utils', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"devtools::install_github('yihui/tikzDevice')\""

################################################################################
#lemon
################################################################################
sudo apt-get -y install cmake
#wget -c http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
tar xvzf lemon-1.3.1.tar.gz
cd lemon-1.3.1
mkdir build
cd build
cmake .. #-DCMAKE_INSTAL_PREFIX='./'
################################################################################
#probably you'll have to comment the thrid line of Cmakelist.txt
#http://stackoverflow.com/questions/35090258/lemon-install-soplex-coin-and-ilog-libraries
################################################################################
make
make check   #(This is optional, but recommended. It runs a bunch of tests.)
sudo make install
cd ../../
rm -rf lemon-1.3.1
