# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assenteAcesso <- function(B, C, D, g, r, eps) {
    .Call('menina_assenteAcesso', PACKAGE = 'menina', B, C, D, g, r, eps)
}

busqueBase <- function(C, D, g, r, eps) {
    .Call('menina_busqueBase', PACKAGE = 'menina', C, D, g, r, eps)
}

computeComponente <- function(D, g, r, eps) {
    .Call('menina_computeComponente', PACKAGE = 'menina', D, g, r, eps)
}

definaDispositivo <- function(g, mu) {
    .Call('menina_definaDispositivo', PACKAGE = 'menina', g, mu)
}

